Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,27 +1,39 @@
-name: build(分工作流)
+name: ace5pro_kpm(分工作流)
 on:
   workflow_call:
     inputs:
       CPU:
         type: string
         required: false
-        default: "sm8750"
+        default: 'sm8750'
+      FEIL:
+        type: string
+        required: false
+        default: 'oneplus_ace5_pro'
+      CPUD:
+        type: string
+        required: false
+        default: 'sun'
       ANDROID_VERSION:
         type: string
         required: false
-        default: "android15"
+        default: 'android15'
       KERNEL_VERSION:
         type: string
         required: false
-        default: "6.6"
+        default: '6.6'
       KERNEL_NAME:
         type: string
         required: false
-        default: "-android15-8-g013ec21bba94-abogki383916444"
+        default: '-android15-8-g013ec21bba94-abogki383916444'
+      kernelsu_variant:
+        type: string
+        required: false
+        default: 'SukiSU-Ultra'
       kernelsu_version:
         type: string
         required: false
-        default: "main"
+        default: 'main'
       SUSFS_ENABLED:
         type: boolean
         required: false
@@ -29,20 +41,13 @@ on:
       VFS_patch_ENABLED:
         type: string
         required: false
-        default: "enable"
+        default: 'enable'
       local_version:
         required: false
         type: string
-        default: "-4k"
 jobs:
   build:
     runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        FEIL: ["oneplus_ace5_pro", "oneplus_13", "oneplus_13t"]
-        optimizer_level: [ "0", "1", "2", "s", "3", "fast"]
-      max-parallel: 1
 
     steps:
       - name: Maximize build space
@@ -51,35 +56,35 @@ jobs:
           root-reserve-mb: 8192
           temp-reserve-mb: 2048
           swap-size-mb: 8192
-          remove-dotnet: "true"
-          remove-android: "true"
-          remove-haskell: "true"
-          remove-codeql: "true"
+          remove-dotnet: 'true'
+          remove-android: 'true'
+          remove-haskell: 'true'
+          remove-codeql: 'true'
 
       - name: Configure Git
         run: |
-          git config --global user.name "jianqing"
-          git config --global user.email "2106456897@qq.com"
+         git config --global user.name "jianqing"
+         git config --global user.email "2106456897@qq.com"
 
-#       - name: Install dependencies
-#         run: |
-#           sudo apt update && sudo apt upgrade -y
-#           sudo apt install -y python3 git curl
+      - name: Install dependencies
+        run: |
+         sudo apt update && sudo apt upgrade -y
+         sudo apt install -y python3 git curl
 
       - name: Install repo tool
         run: |
-          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
-          chmod a+x ~/repo
-          sudo mv ~/repo /usr/local/bin/repo
+         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
+         chmod a+x ~/repo
+         sudo mv ~/repo /usr/local/bin/repo
 
       - name: Initialize repo and sync
         run: |
-          mkdir kernel_workspace && cd kernel_workspace
-          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ matrix.FEIL }}.xml --depth=1
-          repo --trace sync -c -j$(nproc --all) --no-tags
-          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
-          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
-
+         mkdir kernel_workspace && cd kernel_workspace
+         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ inputs.CPU }} -m ${{ inputs.FEIL }}.xml --depth=1
+         repo --trace sync -c -j$(nproc --all) --no-tags
+         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
+         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
+      
       - name: SukiSU-Ultra & SukiSU version
         if: ${{ inputs.kernelsu_variant == 'SukiSU-Ultra' || inputs.kernelsu_variant == 'SukiSU' }}
         run: |
@@ -89,6 +94,26 @@ jobs:
             echo "BRANCH=-s susfs-dev" >> $GITHUB_ENV
           fi
 
+      - name: Add SukiSU-Ultra
+        if: ${{ inputs.kernelsu_variant == 'SukiSU-Ultra' }}
+        run: |
+          cd kernel_workspace/kernel_platform
+          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
+          cd ./KernelSU
+          KSU_VERSION=16384#$(expr $(git rev-list --count main) + 10606)#O3with_perf_support
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          sed -i '/ifeq.*\.git/,/endif/c\KSU_VERSION := 16384\nccflags-y += -DKSU_VERSION=$(KSU_VERSION)\n$(info -- [Fixed] KernelSU version: $(KSU_VERSION))' kernel/Makefile
+
+      - name: Add SukiSU
+        if: ${{ inputs.kernelsu_variant == 'SukiSU' }}
+        run: |
+          cd kernel_workspace/kernel_platform
+          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/KernelSU/main/kernel/setup.sh" | bash ${{ env.BRANCH }}
+          cd ./KernelSU
+          KSU_VERSION=12999#$(expr $(git rev-list --count main) + 10606)
+          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+          sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
+          
       - name: Set up SUSFS & apply patches
         run: |
          set -e
@@ -119,35 +144,26 @@ jobs:
          patch -p1 -F 3 < 1.patch
          echo "✅ SUSFS 和 syscall_hooks patch 应用完成"
 
-
       - name: Apply lz4kd Patches
         run: |
-          set -e
-          cd kernel_workspace/kernel_platform/common
-          PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
-          if [[ -f "$PATCH_FILE" ]]; then
-          cp "$PATCH_FILE" ./lz4kd.patch
-          patch -p1 -F 3 < lz4kd.patch || true
-          else
-          echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
-          fi
+         set -e
+         cd kernel_workspace/kernel_platform/common
+         PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
+         if [[ -f "$PATCH_FILE" ]]; then
+         cp "$PATCH_FILE" ./lz4kd.patch
+         patch -p1 -F 3 < lz4kd.patch || true
+         else
+         echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
+         fi
 
       - name: Set CONFIG_LOCALVERSION
         if: ${{ inputs.local_version != '-4k' }}
         run: |
-          cd kernel_workspace/kernel_platform
-          echo "Using local_version: ${{ inputs.local_version }}"
-          sed -i "s/CONFIG_LOCALVERSION=\"-4k\"/CONFIG_LOCALVERSION=\"${{ inputs.local_version }}\"/" ./common/arch/arm64/configs/gki_defconfig
+         cd kernel_workspace/kernel_platform
+         echo "Using local_version: ${{ inputs.local_version }}"
+         sed -i "s/CONFIG_LOCALVERSION=\"-4k\"/CONFIG_LOCALVERSION=\"${{ inputs.local_version }}\"/" ./common/arch/arm64/configs/gki_defconfig
 
-      - name: Apply Hide Stuff Patches
-        run: |
-          cd kernel_workspace/kernel_platform/common
-          cp ../../SukiSU_patch/69_hide_stuff.patch ./
-          echo "正在打隐藏应用补丁"
-          patch -p1 -F 3 < 69_hide_stuff.patch
-          echo "隐藏应用_patch完成"
-
-      - name: Add SUSFS Configuration SettingsMore actions
+      - name: Add SUSFS Configuration Settings
         run: |
           cd kernel_workspace/kernel_platform
           echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
@@ -178,6 +194,9 @@ jobs:
           echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
+          
+          echo "CONFIG_PERF_EVENTS=y" >> ./common/arch/arm64/configs/gki_defconfig
+          echo "CONFIG_HW_PERF_EVENTS=y" >> ./common/arch/arm64/configs/gki_defconfig
          
           # Remove check_defconfig
           sed -i 's/check_defconfig//' ./common/build.config.gki
@@ -187,57 +206,57 @@ jobs:
 
       - name: Add make name
         run: |
-          cd kernel_workspace/kernel_platform || exit 1
+         cd kernel_workspace/kernel_platform || exit 1
 
-           # 转义特殊字符（防御性处理）
-           ESCAPED_NAME=$(echo "${{ inputs.KERNEL_NAME }}" | sed 's/[\/&]/\\&/g')
+          # 转义特殊字符（防御性处理）
+          ESCAPED_NAME=$(echo "${{ inputs.KERNEL_NAME }}" | sed 's/[\/&]/\\&/g')
 
-           # 使用备选分隔符执行替换
-           sed -i "s|res=\"\$res\$(cat \"\$file\")\"|res=\"${ESCAPED_NAME}\"|g" ./common/scripts/setlocalversion
+          # 使用备选分隔符执行替换
+          sed -i "s|res=\"\$res\$(cat \"\$file\")\"|res=\"${ESCAPED_NAME}\"|g" ./common/scripts/setlocalversion
 
-           # 验证修改结果
-           echo "==== 最终配置 ===="
-           grep 'res=' ./common/scripts/setlocalversion
+          # 验证修改结果
+          echo "==== 最终配置 ===="
+          grep 'res=' ./common/scripts/setlocalversion
 
       - name: Add sched_ext
         run: |
-          cd kernel_workspace/kernel_platform/
-          git clone https://github.com/egcd123/sched_ext.git
-          cp -r ./sched_ext/* ./common/kernel/sched
-          rm -rf ./sched_ext/.git
-          cd common/kernel/sched
-          sed -i.bak '/# include "ext.c"/a\# include "hmbird_sched_proc_main.c"\n#endif\n\n#ifdef CONFIG_SLIM_SCHED\n# include "slim_sysctl.c"' build_policy.c
+         cd kernel_workspace/kernel_platform/
+         git clone https://github.com/egcd123/sched_ext.git
+         cp -r ./sched_ext/* ./common/kernel/sched
+         rm -rf ./sched_ext/.git
+         cd common/kernel/sched
+         sed -i.bak '/# include "ext.c"/a\# include "hmbird_sched_proc_main.c"\n#endif\n\n#ifdef CONFIG_SLIM_SCHED\n# include "slim_sysctl.c"' build_policy.c
 
       - name: Set build timestamp
-        run: |
-          export SOURCE_DATE_EPOCH=$(date -d "2024-12-17 23:36:49 UTC" +%s)
-          echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
-
+        run: |         
+         export SOURCE_DATE_EPOCH=$(date -d "2024-12-17 23:36:49 UTC" +%s)
+         echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
+         
       - name: Build kernel
         run: |
-          cd kernel_workspace/kernel_platform
-          tools/bazel run --config=fast --config=stamp --lto=thin --copt=-O${{ matrix.optimizer_level }} --jobs=$(nproc) --compilation_mode=opt --strip=always --linkopt=-fuse-ld=lld //common:kernel_aarch64_dist -- --dist_dir=dist
-            
+         cd kernel_workspace/kernel_platform
+         tools/bazel run --config=fast --config=stamp --lto=thin --copt=-O3 --jobs=$(nproc) --compilation_mode=opt --strip=always --linkopt=-fuse-ld=lld //common:kernel_aarch64_dist -- --dist_dir=dist
+
       - name: Generate Kernel lmages
         run: |
-          cd kernel_workspace/kernel_platform/dist
-          cp Image Image_original
-          curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
-          chmod +x patch_linux
-          ./patch_linux
-          rm -f Image
-          mv oImage Image
-
+         cd kernel_workspace/kernel_platform/dist
+         cp Image Image_original
+         curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
+         chmod +x patch_linux
+         ./patch_linux
+         rm -f Image
+         mv oImage Image
+         
       - name: Prepare AnyKernel3 Packages
         run: |
-          cd kernel_workspace/kernel_platform/dist
-          git clone https://github.com/egcd123/AnyKernel3.git AnyKernel3-kpm --depth=1
-          rm -rf AnyKernel3-kpm/.git
-          rm -f AnyKernel3-kpm/push.sh
-          cp Image AnyKernel3-kpm/
-
+         cd kernel_workspace/kernel_platform/dist
+         git clone https://github.com/egcd123/AnyKernel3.git AnyKernel3-kpm --depth=1
+         rm -rf AnyKernel3-kpm/.git
+         rm -f AnyKernel3-kpm/push.sh
+         cp Image AnyKernel3-kpm/
+                         
       - name: Upload AnyKernel3 (KPM)
         uses: actions/upload-artifact@v4
         with:
-          name: AnyKernel3_${{ matrix.FEIL }}_${{ env.KSUVER }}_O${{ matrix.optimizer_level }}kpm
-          path: kernel_workspace/kernel_platform/dist/AnyKernel3-kpm/*
+         name: AnyKernel3_oneplus_ace5pro_${{ env.KSUVER }}_kpm
+         path: kernel_workspace/kernel_platform/dist/AnyKernel3-kpm/*
